# **NumPY**
NumPy is a Python library used for working with arrays.
**NumPy stands for Numerical Python.**

The array object in NumPy is called ***ndarray***, it provides a lot of supporting functions that make working with ndarray very easy.






In [ ]:
#Basic understanding
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


**NumPy as np**

NumPy is usually imported under the np alias.

import numpy as np

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


Checking NumPy Version

The version string is stored under "_version_" attribute.

In [ ]:
import numpy as np

print(np.__version__)

2.0.2


# ***Create a NumPy ndarray Object***

NumPy is used to work with arrays.

The array object in **NumPy** is called ndarray.


We can create a NumPy ndarray object by using the **array()** function.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# **ndarray.ndim**
the number of axes (dimensions) of the array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr.ndim

1

# **ndarray.size**

The total number of elements of the array.
This is equal to the product of the elements of shape.

In [ ]:
arr.size

5

# **ndarray.dtype**
An object describing the type of the elements in the array.

In [ ]:
arr.dtype

dtype('int64')

# **ndarray.itemsize**
the size in bytes of each element of the array.

In [ ]:
arr.itemsize

8

# **Array creation**

In [ ]:
# 1 D array
a = np.array([2, 3, 4])
print(a)

[2 3 4]


In [ ]:
#2D array
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
#array with complex numbers
c = np.array([[1, 2], [3, 4]], dtype=complex)
c


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

The function **zeros** creates an array full of zeros.

The function **ones** creates an array full of ones

The function **empty** creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64, but it can be specified via the key word argument dtype.

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

To create sequences of numbers, NumPy provides the **arange** function which returns an array.

In [ ]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [ ]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

# **Indexing, slicing and iterating**

In [ ]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
print(a[4])

64


Slicing in python means taking elements from one given index to another given index.


We pass slice instead of index like this:**[start:end].**


We can also define the step, like this: **[start:end:step].**

In [ ]:
#slicing
print(a[2:5])
print(a[4:])
print(arr[:4])


array([ 8, 27, 64])

In [ ]:
#reverse
a[::-1]  # reversed a

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [ ]:
#iterating
for i in a:
    print(i)

0
1
8
27
64
125
216
343
512
729


**Reshaping arrays**
Reshaping means changing the shape of an array.


The shape of an array is the number of elements in each dimension.


By reshaping we can add or remove dimensions or change number of elements in each dimension.



In [ ]:
# 1D to 2D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#1D to 3D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**Flattening the arrays**

Flattening array means converting a multidimensional array into a 1D array.


We can use reshape(-1) to do this.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


# **Other** **examples**

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Basic array operations

print("Original array", arr)
print("Array dtype:", arr.dtype)
print("Array shape: ", arr.shape)
print("Add 5 to each element:", arr + 5)
print("Subtract 2 from each element", arr - 2)
print("Multiply each element by 3", arr * 3)
print("Divide each element by 2: ", arr / 2)

Original array [10 20 30 40 50]
Array dtype: int64
Array shape:  (5,)
Add 5 to each element: [15 25 35 45 55]
Subtract 2 from each element [ 8 18 28 38 48]
Multiply each element by 3 [ 30  60  90 120 150]
Divide each element by 2:  [ 5. 10. 15. 20. 25.]


In [ ]:
import numpy as np

# Creating 1D arrays
arr_1d = np.array([1, 2, 3, 4, 5])

# Creating 2D arrays
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Displaying arrays
print("1D Array:")
print(arr_1d)
print()

print("2D Array:")
print(arr_2d)
print()

# Accessing elements
print("Accessing elements:")
print("First element of 1D array:", arr_1d[0])
print("Element at position (1,1) in 2D array:", arr_2d[1, 1])
print()

# Slicing arrays
print("Slicing arrays:")
print("Slice from index 1 to 3 in 1D array:", arr_1d[1:4])
print("Slice first row of 2D array:", arr_2d[0, :])
print()

# Array shape and dimensions
print("Shape and dimensions:")
print("Shape of 1D array:", arr_1d.shape)
print("Shape of 2D array:", arr_2d.shape)
print("Number of dimensions of 1D array:", arr_1d.ndim)
print("Number of dimensions of 2D array:", arr_2d.ndim)
print()

In [ ]:
# Reshaping arrays
reshaped_arr = np.reshape(arr_1d, (5, 1))  # Reshape 1D array into a 5x1 matrix
print("Reshaped array (5x1):")
print(reshaped_arr)
print()

# Element-wise operations
print("Element-wise operations:")
addition = arr_1d + 2
print("Adding 2 to each element of 1D array:", addition)
multiplication = arr_2d * 2
print("Multiplying each element of 2D array by 2:")
print(multiplication)
print()

# Aggregation functions
print("Aggregation functions:")
print("Sum of all elements in 1D array:", np.sum(arr_1d))
print("Minimum element in 2D array:", np.min(arr_2d))
print("Maximum element in 2D array:", np.max(arr_2d))
print("Mean of all elements in 2D array:", np.mean(arr_2d))
print()

# Transposing arrays
print("Transposing arrays:")
transposed_arr = np.transpose(arr_2d)
print("Transposed 2D array:")
print(transposed_arr)
print()

# Concatenating arrays
arr_concatenated = np.concatenate((arr_2d, arr_2d), axis=1)
print("Concatenated 2D array along axis 1:")
print(arr_concatenated)


https://numpy.org/
https://numpy.org/devdocs/user/quickstart.html
https://www.w3schools.com/python/numpy/numpy_intro.asp
